#define CHARACTERS_TYPE Regs

CLASS_ARF_VEST(Base);
CLASS_ENGINEER_VEST(Base);
CLASS_ENGINEERNCO_VEST(Base);
CLASS_FORCERECONNCO_VEST(Base);
CLASS_HAZARD_VEST(Base);
CLASS_HEAVY_VEST(Base);
CLASS_ARCPLATE_VEST(Base);
CLASS_ASSAULT_VEST(Base);
CLASS_CFR_VEST(Base);
CLASS_GRENADIER_VEST(Base);
CLASS_KAMA_VEST(Base);
CLASS_LIEUTENANT_VEST(Base);
CLASS_MEDIC_VEST(Base);
CLASS_OFFICER_VEST(Base);
CLASS_RECON_VEST(Base);
CLASS_RECONNCO_VEST(Base);
CLASS_SPECIALIST_VEST(Base);
CLASS_CLONE_VEST(Base);

#undef CHARACTERS_TYPE
