#define CHARACTERS_TYPE Regs

CLASS_UNIFORM_F(Shiny);
CLASS_UNIFORM_F(DOUBLES(Shiny,EOD));
CLASS_UNIFORM_F(DOUBLES(Shiny,Medic));

CLASS_UNIFORM_F(Trooper);
CLASS_UNIFORM_F(DOUBLES(Trooper,EOD));
CLASS_UNIFORM_F(DOUBLES(Trooper,Medic));

#undef CHARACTERS_TYPE
