#define CHARACTERS_TYPE Regs

CLASS_UNIFORM(Shiny);
CLASS_UNIFORM(DOUBLES(Shiny,EOD));
CLASS_UNIFORM(DOUBLES(Shiny,Medic));

CLASS_UNIFORM(Trooper);
CLASS_UNIFORM(DOUBLES(Trooper,EOD));
CLASS_UNIFORM(DOUBLES(Trooper,Medic));

#undef CHARACTERS_TYPE
