class CfgWorlds {
    initWorld = "VR";
    demoWorld = "VR";
    class CAWorld;
    WORLD_CUTSCENE(3AS_Orto_Plut);
    WORLD_CUTSCENE(3AS_Sullust);
    WORLD_CUTSCENE(3as_Tatooine);
    WORLD_CUTSCENE(Altis);
    WORLD_CUTSCENE(Blood_OPTRE);
    WORLD_CUTSCENE(Enoch);
    WORLD_CUTSCENE(Jabiim);
    WORLD_CUTSCENE(Kamino);
    WORLD_CUTSCENE(Malden);
    WORLD_CUTSCENE(OPTRE_EridanusSecundus);
    WORLD_CUTSCENE(OPTRE_Gridlock);
    WORLD_CUTSCENE(OPTRE_Harvest);
    WORLD_CUTSCENE(OPTRE_Kholo);
    WORLD_CUTSCENE(OPTRE_Madrigal);
    WORLD_CUTSCENE(OPTRE_Phobos);
    WORLD_CUTSCENE(OPTRE_Roost);
    WORLD_CUTSCENE(OPTRE_Sandstorm);
    WORLD_CUTSCENE(OPTRE_iberius);
    WORLD_CUTSCENE(Rugosa);
    WORLD_CUTSCENE(Space2);
    WORLD_CUTSCENE(Stratis);
    WORLD_CUTSCENE(TKE_Ext_Europa);
    WORLD_CUTSCENE(TKE_Ext_Ganymede);
    WORLD_CUTSCENE(Tanoa);
    WORLD_CUTSCENE(VR);
    WORLD_CUTSCENE(egl_gliese);
    WORLD_CUTSCENE(egl_gliese581xeast);
    WORLD_CUTSCENE(egl_gliese581xnorth);
    WORLD_CUTSCENE(egl_gliese581xsouth);
    WORLD_CUTSCENE(egl_lv426);
    WORLD_CUTSCENE(egl_miranda);
    WORLD_CUTSCENE(jns_Ritov);
    WORLD_CUTSCENE(lsb_terrain_endor);
    WORLD_CUTSCENE(lsb_terrain_geonosis);
    WORLD_CUTSCENE(lsb_terrain_geonosis2);
    WORLD_CUTSCENE(lsb_terrain_mimban);
    WORLD_CUTSCENE(lsb_terrain_scarif);
};
