[Default]

Version = 1
;; Used incase there is ever a breaking change, or to inform user in log about a new feature.

Strip Chars = ";"
;; List of characters to strip out

Strip Chars Mode = 0
;; 0 = Strip Bad Chars, 1 = Strip + Log Bad Chars, 2 = Return Error & Log Bad Chars
;;     Note: Logging on works when sending data to database.

Input SQF Parser = false
;; Expermential
;;   If enabled will use SQF Array Parser instead of : seperator for values
;;   i.e   0:SQL:UpdatePlayer:["Joe",[1,2,0],0.22333,"PlayerBackpack",-3]
;;   Advantage is that you don't need to strip : seperator from user inputted values

Number of Retrys = 5
;; Number of Retrys if Error Encountered
;;  Note: If doing multiple SQL i.e SQL1_1 SQL2_1 etc, it will retry everything.

[getPlayerProfileBySteamId]
;; 1 = steam_id

SQL1_1 = SELECT money, grade, is_medic, is_eod, loadout FROM arma3_player_profiles WHERE steam_id=?
SQL1_INPUTS = 1
OUTPUT = 1

[insertOrUpdatePlayerProfileBySteamId]
;; 1 = steam_id
;; 2 = ingame_name
;; 3 = is_medic
;; 4 = is_eod
;; 5 = loadout

SQL1_1 = INSERT INTO arma3_player_profiles (steam_id, ingame_name, is_medic, is_eod, loadout, last_online) SELECT ?, ?, ?, ?, ?, NOW() WHERE EXISTS (SELECT 1 FROM users WHERE steam_id=?) ON DUPLICATE KEY UPDATE ingame_name=?, is_medic=?, is_eod=?, loadout=?, last_online=NOW()
SQL1_INPUTS = 1,2-string2,3,4,5-string2,1,2-string2,3,4,5-string2

[addMoneyToPlayerProfileBySteamId]
;; 1 = steam_id
;; 2 = amount

SQL1_1 = INSERT INTO arma3_player_profiles (steam_id, money) SELECT ?, ? WHERE EXISTS (SELECT 1 FROM users WHERE steam_id=?) ON DUPLICATE KEY UPDATE money=money+?
SQL1_INPUTS = 1,2,1,2

[insertPlayerAttendanceBySteamId]
;; 1 = steam_id

SQL1_1 = INSERT INTO operation_arma3_attendance (steam_id, joined_at) VALUES (?, NOW())
SQL1_INPUTS = 1

[closePlayerAttendanceBySteamId]
;; 1 = steam_id

SQL1_1 = UPDATE operation_arma3_attendance SET left_at = NOW() WHERE steam_id = ? AND left_at IS NULL ORDER BY joined_at DESC LIMIT 1
SQL1_INPUTS = 1

[closeRecentAttendances]

SQL1_1 = UPDATE operation_arma3_attendance SET left_at = NOW() WHERE left_at IS NULL AND joined_at >= DATE_SUB(NOW(), INTERVAL 12 HOUR)
