name = "[16th] - Phoenix Company"
author = "PhoenixTEAM"
prefix = "PC"
mainprefix = "x"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "*.paa",
    "*.dll",
    "LICENSE.md",
    "README.md",
]
exclude = [
    "*.psd",
    "*.png",
    "*.md",
]

[properties]
author = "PhoenixTEAM"
