#define CHARACTERS_TYPE Regs

CLASS_MEDIC_BACKPACK(Base);
CLASS_STANDARD_BACKPACK(Base);
CLASS_STANDARD_BACKPACK(EOD);
CLASS_RADIO_BACKPACK(Base);
CLASS_ROCKET_BACKPACK(Base);
CLASS_INVISIBLE_BACKPACK(Base);

#undef CHARACTERS_TYPE
